% checks the paths have been set
if ~exist('sw_rootdir')
	addpath(genpath('spinw'));
end

[src, ~, ~] = fileparts(mfilename('fullpath'));

% compile the code
swr = fileparts(sw_rootdir);
mccCommand = ['mcc -W python:spinw -v -N '...
    '-d ' src ' ' ...
    '-a ' swr '/dat_files/* '...
    '-a ' swr '/external '...
    '-a ' swr '/swfiles '...
    'transpose.m '...
    src '/ass.m '...
    src '/ev.m '...
    src '/evo.m '...
    src '/prcasrmn2o7.m '...
    src '/dimer.m '...
    src '/zener_polaron.m '...
    src '/sw_main.m'];

eval(mccCommand);
